version: 2
jobs:
  build1_bobby:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Hello World"
  build2_sally:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Double trouble"
workflow:
  version: 2
  bobby_sally:
    jobs:
      - build1_bobby
      - build2_sally